config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cohorts, only: [:index, :new, :create, :show]
  resources :timespans, only: [:index]

  get 'cohort_summaries', to: 'cohort_summaries#index', as: :cohort_summaries
  get 'cohort/:id/timespan/:timespan_id', to: 'cohort_summaries#show'
  put 'cohort/:id/timespan/:timespan_id', to: 'cohort_summaries#update', as: :cohort_summary_receiver

  get 'cohort_comparisons', to: 'cohort_comparisons#index', as: :cohort_comparisons
  get 'cohort_comparisons/:id', to: 'cohort_comparisons#show'
  get 'cohort/:cohort_a_id/timespan/:timespan_a_id/cohort/:cohort_b_id/timespan/:timespan_b_id',
    to: 'cohort_comparisons#show'
  put 'cohort/:cohort_a_id/timespan/:timespan_a_id/cohort/:cohort_b_id/timespan/:timespan_b_id',
    to: 'cohort_comparisons#update', as: :cohort_comparison_receiver
  #put 'cohort/:cohort_a_id/timespan/:timespan_a_id/cohort/:cohort_b_id/timespan/:timespan_b_id',
    #to: 'cohort_comparisons#update', as: :cohort_comparison_receiver

  devise_for :users
  devise_for :api_users,
             defaults: { format: :json },
             class_name: 'ApiUser',
             skip: %i[
               registrations invitations
               passwords confirmations
               unlocks
             ],
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }
  devise_scope :api_user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  root to: 'home#index', as: 'home'

  match '*all', to: 'application#cors_preflight_check', via: :options
end

app/models/cohort.rb
# == Schema Information
#
# Table name: cohorts
#
#  id           :bigint           not null, primary key
#  description  :text
#  index_prefix :string
#  name         :text
#  twitter_ids  :text             default([]), is an Array
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Cohort < ApplicationRecord
  after_save :update_data_collection

  private

  def update_data_collection
    StreamingDataCollector.write_conf
  end
end

app/controllers/cohort_controller.rb
class CohortController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
    render json: CohortSerializer.new(
      CohortSerializer.where(active: true)
    ).serialized_json
  end

  def show
    if params.include? :id
      show_one
    elsif params.include? :ids
      show_multiple
    else
      raise ActionController::ParameterMissing('/:id or ?ids[]=1&ids[]=2 must be supplied')
    end
  end

  private

  def show_one
    render json: CohortSerializer.new(
      Cohort.find(params[:id])
    ).serialized_json
  end

  # Given a list of cohort IDs, returns the most recent data sets for each, plus
  # the aggregated data across all.
  # Expects a querystring of the form ids[]=1&ids[]=2&ids[]=3.
  def show_multiple
    data = CohortSerializer.new(
      Cohort.where(id: params[:ids]), is_collection: true
    ).serializable_hash

    unless params_valid?
      data[:errors] = 'One or more specified Cohorts do not exist'
    end

    render json: data.to_json
  end

  def params_valid?
    # Each requested parameter should correspond to a Cohort that actually
    # exists, meaning that the number of parameters should equal the number of
    # Cohorts fetched from the db.
    # If someone has entered non-numeric params, they'll map to 0, so there's
    # no error to handle.
    integer_ids = params[:ids].map(&:to_i).reject { |i| i == 0 }
    integer_ids.length == Cohort.where(id: params[:ids]).count
  end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :verify_admin, only: [:new, :create]
  after_action { flash.discard if request.xhr? }
  respond_to :html, :json, :js

  def index
    return index_json unless current_user.admin?

    respond_to do |format|
      format.json { index_json }
      format.csv { index_csv }
      format.html
    end
  end

  def show
    return show_json unless current_user.admin?

    @cohort = Cohort.find(params[:id])

    respond_to do |format|
      format.json { show_json }
      format.csv { show_csv }
      format.html
    end
  end

  def create
    @cohort = Cohort.new(cohort_params)

    if @cohort.save
      flash[:info] = 'Cohort created'
      redirect_to cohort_path(@cohort)
    else
      render 'new'
    end
  end

  def collect_data
    Cohort.find(params[:cohort_id]).collect_data

    flash[:info] = 'Data collection in process'
  rescue Faraday::ConnectionFailed => error
    Rails.logger.warn("Failed collection data for cohort #{params[:cohort_id]}: #{error}")
    flash[:warning] = "Data can't be collected because Elasticsearch isn't running. Talk to the geeks."
  rescue Exception => error
    Rails.logger.warn("Failed collection data for cohort #{params[:cohort_id]}: #{error}")
    flash[:warning] = 'Something went wrong.'
  ensure
    respond_to do |format|
      format.js
    end
  end

  private

  def index_json
    return show_multiple if params.include? :ids

    render json: CohortSerializer.new(
      Cohort.all
    ).serialized_json
  end

  def show_json
    render json: CohortSerializer.new(
      Cohort.find(params[:id])
    ).serialized_json
  end

  def index_csv
    render csv: Cohort.all
  end

  def show_csv
    if params.include? :id
      render csv: Cohort.find(params[:id])
    else
      raise ActionController::BadRequest
    end
  end

  def show_one
  end

  # Given a list of cohort IDs, returns the most recent data sets for each, plus
  # the aggregated data across all.
  # Expects a querystring of the form ids[]=1&ids[]=2&ids[]=3.
  def show_multiple
    data = CohortSerializer.new(
      Cohort.where(id: params[:ids]), is_collection: true
    ).serializable_hash

    unless params_valid?
      data[:errors] = 'One or more specified Cohorts do not exist'
    end

    render json: data.to_json
  end

  def params_valid?
    # Each requested parameter should correspond to a Cohort that actually
    # exists, meaning that the number of parameters should equal the number of
    # Cohorts fetched from the db.
    # If someone has entered non-numeric params, they'll map to 0, so there's
    # no error to handle.
    integer_ids = params[:ids].map(&:to_i).reject { |i| i == 0 }
    integer_ids.length == Cohort.where(id: params[:ids]).count
  end

  def cohort_params
    params.permit(:description)
          .merge({ twitter_ids: params[:twitter_ids].split(',').map(&:strip) })
  end

  def verify_admin
    return head :unauthorized unless current_user.admin?
  end
end

app/views/cohorts/collect_data.js.erb
$('#collect_data_flash').replaceWith("<%= j(render 'shared/flashes') %>");

app/views/cohorts/index.html.erb
<h1 class="title is-3">Cohorts</h1>

<%= link_to "Create manually", new_cohort_path, class: 'button' %>

<h2 class="title is-5">Existing Cohorts</h2>

<ul class="list is-marginless">
  <% Cohort.all.each do |cohort| %>
    <li class="list-item">
      <%= cohort.id %>. <%= link_to cohort.description, cohort %>
    </li>
  <% end %>
</ul>

app/views/cohorts/new.html.erb
<h1 class="title is-3">Create new Cohort <span class="is-size-7"><a href="#about">what's this?</a></span></h1>

<div class="box">
  <%= form_with model: Cohort.new, url: cohorts_path do |f| %>
    <div class="field">
      <label class="label" for="twitter_ids">Twitter IDs</label>
      <div class="control">
        <input class="input" type="text" placeholder="14706139, 19259102, 20095468" name="twitter_ids" id="twitter_ids">
      </div>
    </div>

    <div class="field">
      <label class="label" for="description">Description</label>
      <div class="control">
        <textarea class="textarea" placeholder="Description" name="description" id="description"></textarea>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.submit 'Create' , class: 'button is-primary'%>
      </div>
    </div>
  <% end %>
</div>

<div class="card" id="about">
  <header class="card-header">
    <p class="card-header-title">
      About Cohorts
    </p>
  </header>
  <div class="card-content">
    <div class="content">
      <p>
        A Cohort:
      </p>

      <ol>
        <li>Is a group of Twitter users (identified by ID)</li>
        <li>Can pull data from those users' recent timelines.</li>
      </ol>

      <p>
        The description will be publicly displayed to end users.
      </p>
    </div>
  </div>
</div>

app/views/cohorts/show.html.erb
<h1 class="title is-3">Cohort #<%= @cohort.id %></h1>

<div id='collect_data_flash'></div>
<%= button_to 'Start collecting data (may take a while...)',
              cohort_collect_data_path(@cohort),
              remote: true,
              class: 'button' %>

<table class="table is-hoverable is-striped">
  <tbody>
    <tr>
      <th>Description</th>
      <td><%= @cohort.description %></td>
    </tr>
    <tr>
      <th>Twitter IDs</th>
      <td><%= @cohort.twitter_ids %></td>
    </tr>
  </tbody>
</table>